#!/usr/bin/env python
import boto3
import os
import json
from zipfile import ZipFile
import shutil

codePipelineClient = boto3.client('codepipeline')
s3Client = boto3.resource('s3')

sourcedir=os.environ['CODEBUILD_SRC_DIR']
includeList=[]
if 'Artifacts_Included' in os.environ:
    includeList=os.environ['Artifacts_Included'].split(',')

excludeList=[]
if 'Artifacts_Excluded' in os.environ:
    excludeList=os.environ['Artifacts_Excluded'].split(',')

codebuildInitiator=os.environ['CODEBUILD_INITIATOR']
print(codebuildInitiator)
codePipelineName=codebuildInitiator[13:]

print("\n\nProcessing source for "+codePipelineName+'\n\n')
print("IncludeList -> "+",".join(str(x) for x in includeList))
print("ExcludeList -> "+",".join(str(x) for x in excludeList))

pipelineData = codePipelineClient.get_pipeline(
    name=codePipelineName
)

#clean source path
#we have to prodive at least one artifact to CodeBuild, however
#as the user can choose to later excluded it, we need to ensure
#the working dir is clean
print('\n\nCleaning Source Directory')
print(' -- '+sourcedir)
for root, dirs, files in os.walk(sourcedir):
    for f in files:
        os.unlink(os.path.join(root, f))
    for d in dirs:
        shutil.rmtree(os.path.join(root, d))


print ("Getting artifacts from CodePipeline")
#Get artifacts
artifacts=[]
for stage in pipelineData['pipeline']['stages']:
  for action in stage['actions']:
    if action['actionTypeId']['category']=='Source':
     artifactName=action['outputArtifacts'][0]['name']
     if 'S3Bucket' in action['configuration']:
      bucket =  action['configuration']['S3Bucket']
      object = action['configuration']['S3ObjectKey']
      uri='s3://'+bucket+'/'+object
      uriObj={}
      uriObj['bucket']=bucket
      uriObj['key']=object
      uriObj['name']=artifactName
      print (' -- Found S3 Source: '+uri)

      if (len(includeList)==0 and artifactName in excludeList):
        print(' -- [skipping -> excluded]')
      elif (len(includeList)>0 and artifactName not in includeList):
        print(' -- [skipping -> not included]')
      else:
        artifacts.append(uriObj)
        print(' -- [added]')


#Get source artifacts and unzip
print ('\n\nDownloading Artifacts')
for artifact in artifacts:
    file=artifact['key']
    bucket=artifact['bucket']
    print(" -- Downloading "+bucket+'/'+file)
    s3Client.meta.client.download_file(bucket,file, sourcedir+'/'+file)
    ext=os.path.splitext(file)[1]
    if (ext=='.zip'):
        print(" ---- Unzipping "+file)
        zf=ZipFile(sourcedir+'/'+file,'r')
        zf.extractall(sourcedir)
        os.remove(sourcedir+'/'+file)

#List expected artifacts
print('\n\nStructure to be packaged:');
for dirname, dirnames, filenames in os.walk(sourcedir):
    # print path to all subdirectories first.
    for subdirname in dirnames:
        print(' -- '+os.path.join(dirname, subdirname))

    # print path to all filenames.
    for filename in filenames:
        print(' -- '+os.path.join(dirname, filename))

print('\n\nDONE\n\n')
